# Generated by Django 5.2.1 on 2025-05-21 12:27

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, verbose_name='Номер телефона'),
        ),
    ]
