# Generated by Django 5.2.1 on 2025-05-19 12:54

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('mailing_address', models.TextField(blank=True, null=True, verbose_name='Почтовый адрес')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='personal_diary/images', validators=[users.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .', 'Недопустимое расширение!')], verbose_name='Изображение')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Запись в дневнике',
                'verbose_name_plural': 'Записи в дневнике',
                'ordering': ['owner', 'updated_at', 'title'],
            },
        ),
    ]
