# Generated by Django 5.2.1 on 2025-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
