# Generated by Django 5.2.1 on 2025-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0004_diaryentry_reminder_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='reminder_time',
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания'),
        ),
    ]
