# Generated by Django 5.2.1 on 2025-05-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0006_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='time',
        ),
    ]
