# Generated by Django 5.2.1 on 2025-05-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0007_remove_calendar_datetime_remove_calendar_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
