# Generated by Django 5.2.1 on 2025-05-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0008_delete_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['mailing_address'], 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
