# Generated by Django 5.2.1 on 2025-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_diary', '0010_alter_diaryentry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
